### ISSUE TITLE
refactor: `InlineFormItem` as standalone component

### ISSUE THREAD

**Issue by specialdoom** [specialdoom/proi-ui#119]
Creation of a new component, `InlineFormItem`, which will serve as a separate component specifically designed for the inline variant of the existing `FormItem` component. Currently, the inline variant is available as a standalone component, but not exported as a standalone component but as a variant of the `FormItem` component.

### Tasks

- [x] Export the existing `InlineFormItem` as a separate component of the lib.
- [x] Update the documentation to include information about the new `InlineFormItem` component.
- [x] Separate inline variant stories related to `InlineFormItem`.
- [x] Search and identify instances of the `FormItem` component where the inline variant is used.
- [x] Replace those instances with the new `InlineFormItem` component.
- [x] Ensure that the migration is seamless and does not introduce any regressions or compatibility issues.

### Deliverables:

- Export of `InlineFormItem` component.
- Updated documentation reflecting the export of the `InlineFormItem` component.
- New stories grouped under `form-item` section.
